
test_that("tensors can be created", {
  t <- as_tf_tensor(matrix(1))
  expect_identical(as_tf_tensor(t), t)
  expect_s3_class(t, "tf_tensor")
  expect_match(format(t), "<tf_tensor<DOUBLE")
  expect_output(print(t), "<tf_tensor<DOUBLE")

  attrs <- tf_tensor_attributes(t)
  expect_identical(attrs$data_type, 2L)
  expect_identical(attrs$data_type_label, "DOUBLE")
  expect_identical(attrs$length, 1)
  expect_identical(attrs$num_dims, 2L)
  expect_identical(attrs$shape, c(1, 1))

  expect_identical(
    tf_tensor_attributes(tf_tensor_clone(t)),
    tf_tensor_attributes(t)
  )

  expect_identical(as.array(t), as.array(matrix(1)))
})

test_that("tf_tensor() can be rountripped through raw()", {
  arr <- array(as.numeric(1:12), dim = c(2, 6))
  ten <- as_tf_tensor(arr, .tf_ptype = "UINT8")
  expect_identical(tf_tensor_to_bytes(ten), as.raw(t(as.array(ten, .ptype = raw()))))
  expect_identical(
    as.array(
      tf_tensor_from_bytes(
        tf_tensor_to_bytes(ten),
        dim = c(2, 6),
        .tf_ptype = tf_ptype_from_label("UINT8")
      ),
      .ptype = double()
    ),
    arr
  )
})

test_that("tf_tensor() to array conversion works (shape)", {
  arr <- array(as.numeric(1:12), dim = c(2, 6))
  ten <- as_tf_tensor(arr)
  expect_identical(as.array(ten), arr)

  arr <- array(as.numeric(1:24), dim = c(2, 3, 4))
  ten <- as_tf_tensor(arr)
  expect_identical(as.array(ten), arr)
})

test_that("tf_tensor() to array conversion works (type)", {
  arr <- array(as.numeric(0:11), dim = c(2, 6))

  tensor_bool <- as_tf_tensor(arr, .tf_ptype = "BOOL")
  tensor_float <- as_tf_tensor(arr, .tf_ptype = "FLOAT")
  tensor_double <- as_tf_tensor(arr, .tf_ptype = "DOUBLE")
  tensor_int8 <- as_tf_tensor(arr, .tf_ptype = "INT8")
  tensor_int16 <- as_tf_tensor(arr, .tf_ptype = "INT16")
  tensor_int32 <- as_tf_tensor(arr, .tf_ptype = "INT32")
  tensor_int64 <- as_tf_tensor(arr, .tf_ptype = "INT64")
  tensor_uint8 <- as_tf_tensor(arr, .tf_ptype = "UINT8")
  tensor_uint16 <- as_tf_tensor(arr, .tf_ptype = "UINT16")
  tensor_uint32 <- as_tf_tensor(arr, .tf_ptype = "UINT32")
  tensor_uint64 <- as_tf_tensor(arr, .tf_ptype = "UINT64")

  expect_identical(tf_tensor_attributes(tensor_bool)$data_type_label, "BOOL")
  expect_identical(tf_tensor_attributes(tensor_float)$data_type_label, "FLOAT")
  expect_identical(tf_tensor_attributes(tensor_double)$data_type_label, "DOUBLE")
  expect_identical(tf_tensor_attributes(tensor_int8)$data_type_label, "INT8")
  expect_identical(tf_tensor_attributes(tensor_int16)$data_type_label, "INT16")
  expect_identical(tf_tensor_attributes(tensor_int32)$data_type_label, "INT32")
  expect_identical(tf_tensor_attributes(tensor_int64)$data_type_label, "INT64")
  expect_identical(tf_tensor_attributes(tensor_uint8)$data_type_label, "UINT8")
  expect_identical(tf_tensor_attributes(tensor_uint16)$data_type_label, "UINT16")
  expect_identical(tf_tensor_attributes(tensor_uint32)$data_type_label, "UINT32")
  expect_identical(tf_tensor_attributes(tensor_uint64)$data_type_label, "UINT64")
})

test_that("tf_tensor() can roundtrip a double() array", {
  arr <- array(as.numeric(0:11), dim = c(2, 6))
  arr_int <- array(0:11, dim = c(2, 6))
  arr_raw <- array(as.raw(0:11), dim = c(2, 6))

  tensor_bool <- as_tf_tensor(arr, .tf_ptype = "BOOL")
  tensor_float <- as_tf_tensor(arr, .tf_ptype = "FLOAT")
  tensor_double <- as_tf_tensor(arr, .tf_ptype = "DOUBLE")
  tensor_int8 <- as_tf_tensor(arr, .tf_ptype = "INT8")
  tensor_int16 <- as_tf_tensor(arr, .tf_ptype = "INT16")
  tensor_int32 <- as_tf_tensor(arr, .tf_ptype = "INT32")
  tensor_int64 <- as_tf_tensor(arr, .tf_ptype = "INT64")
  tensor_uint8 <- as_tf_tensor(arr, .tf_ptype = "UINT8")
  tensor_uint16 <- as_tf_tensor(arr, .tf_ptype = "UINT16")
  tensor_uint32 <- as_tf_tensor(arr, .tf_ptype = "UINT32")
  tensor_uint64 <- as_tf_tensor(arr, .tf_ptype = "UINT64")

  expect_identical(as.array(tensor_bool, .ptype = double()), arr)
  expect_identical(as.array(tensor_float, .ptype = double()), arr)
  expect_identical(as.array(tensor_double, .ptype = double()), arr)
  expect_identical(as.array(tensor_int8, .ptype = double()), arr)
  expect_identical(as.array(tensor_int16, .ptype = double()), arr)
  expect_identical(as.array(tensor_int32, .ptype = double()), arr)
  expect_identical(as.array(tensor_int64, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint8, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint16, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint32, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint64, .ptype = double()), arr)

  expect_identical(as.array(tensor_bool, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_float, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_double, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int64, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint64, .ptype = integer()), arr_int)

  expect_identical(as.array(tensor_uint8, .ptype = raw()), arr_raw)
  expect_identical(as.array(tensor_bool, .ptype = logical()), arr != 0)
})

test_that("tf_tensor() can roundtrip a integer() array", {
  arr <- array(as.numeric(0:11), dim = c(2, 6))
  arr_int <- array(0:11, dim = c(2, 6))
  arr_raw <- array(as.raw(0:11), dim = c(2, 6))

  tensor_bool <- as_tf_tensor(arr_int, .tf_ptype = "BOOL")
  tensor_float <- as_tf_tensor(arr_int, .tf_ptype = "FLOAT")
  tensor_double <- as_tf_tensor(arr_int, .tf_ptype = "DOUBLE")
  tensor_int8 <- as_tf_tensor(arr_int, .tf_ptype = "INT8")
  tensor_int16 <- as_tf_tensor(arr_int, .tf_ptype = "INT16")
  tensor_int32 <- as_tf_tensor(arr_int, .tf_ptype = "INT32")
  tensor_int64 <- as_tf_tensor(arr_int, .tf_ptype = "INT64")
  tensor_uint8 <- as_tf_tensor(arr_int, .tf_ptype = "UINT8")
  tensor_uint16 <- as_tf_tensor(arr_int, .tf_ptype = "UINT16")
  tensor_uint32 <- as_tf_tensor(arr_int, .tf_ptype = "UINT32")
  tensor_uint64 <- as_tf_tensor(arr_int, .tf_ptype = "UINT64")

  expect_identical(as.array(tensor_bool, .ptype = double()), arr)
  expect_identical(as.array(tensor_float, .ptype = double()), arr)
  expect_identical(as.array(tensor_double, .ptype = double()), arr)
  expect_identical(as.array(tensor_int8, .ptype = double()), arr)
  expect_identical(as.array(tensor_int16, .ptype = double()), arr)
  expect_identical(as.array(tensor_int32, .ptype = double()), arr)
  expect_identical(as.array(tensor_int64, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint8, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint16, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint32, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint64, .ptype = double()), arr)

  expect_identical(as.array(tensor_bool, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_float, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_double, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int64, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint64, .ptype = integer()), arr_int)

  expect_identical(as.array(tensor_uint8, .ptype = raw()), arr_raw)
  expect_identical(as.array(tensor_bool, .ptype = logical()), arr != 0)
})

test_that("tf_tensor() can roundtrip a raw() array", {
  arr <- array(as.numeric(0:11), dim = c(2, 6))
  arr_int <- array(0:11, dim = c(2, 6))
  arr_raw <- array(as.raw(0:11), dim = c(2, 6))

  tensor_bool <- as_tf_tensor(arr_raw, .tf_ptype = "BOOL")
  tensor_float <- as_tf_tensor(arr_raw, .tf_ptype = "FLOAT")
  tensor_double <- as_tf_tensor(arr_raw, .tf_ptype = "DOUBLE")
  tensor_int8 <- as_tf_tensor(arr_raw, .tf_ptype = "INT8")
  tensor_int16 <- as_tf_tensor(arr_raw, .tf_ptype = "INT16")
  tensor_int32 <- as_tf_tensor(arr_raw, .tf_ptype = "INT32")
  tensor_int64 <- as_tf_tensor(arr_raw, .tf_ptype = "INT64")
  tensor_uint8 <- as_tf_tensor(arr_raw, .tf_ptype = "UINT8")
  tensor_uint16 <- as_tf_tensor(arr_raw, .tf_ptype = "UINT16")
  tensor_uint32 <- as_tf_tensor(arr_raw, .tf_ptype = "UINT32")
  tensor_uint64 <- as_tf_tensor(arr_raw, .tf_ptype = "UINT64")

  expect_identical(as.array(tensor_bool, .ptype = double()), arr)
  expect_identical(as.array(tensor_float, .ptype = double()), arr)
  expect_identical(as.array(tensor_double, .ptype = double()), arr)
  expect_identical(as.array(tensor_int8, .ptype = double()), arr)
  expect_identical(as.array(tensor_int16, .ptype = double()), arr)
  expect_identical(as.array(tensor_int32, .ptype = double()), arr)
  expect_identical(as.array(tensor_int64, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint8, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint16, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint32, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint64, .ptype = double()), arr)

  expect_identical(as.array(tensor_bool, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_float, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_double, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int64, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint64, .ptype = integer()), arr_int)

  expect_identical(as.array(tensor_uint8, .ptype = raw()), arr_raw)
  expect_identical(as.array(tensor_bool, .ptype = logical()), arr != 0)
})

test_that("tf_tensor() can roundtrip a logical() array", {
  arr <- (array(as.numeric(0:11), dim = c(2, 6)) != 0) * 1
  arr_int <- (array(0:11, dim = c(2, 6)) != 0) * 1L
  arr_raw <- array(as.raw(c(0, rep(1, 11))), dim = c(2, 6))

  tensor_bool <- as_tf_tensor(arr != 0, .tf_ptype = "BOOL")
  tensor_float <- as_tf_tensor(arr != 0, .tf_ptype = "FLOAT")
  tensor_double <- as_tf_tensor(arr != 0, .tf_ptype = "DOUBLE")
  tensor_int8 <- as_tf_tensor(arr != 0, .tf_ptype = "INT8")
  tensor_int16 <- as_tf_tensor(arr != 0, .tf_ptype = "INT16")
  tensor_int32 <- as_tf_tensor(arr != 0, .tf_ptype = "INT32")
  tensor_int64 <- as_tf_tensor(arr != 0, .tf_ptype = "INT64")
  tensor_uint8 <- as_tf_tensor(arr != 0, .tf_ptype = "UINT8")
  tensor_uint16 <- as_tf_tensor(arr != 0, .tf_ptype = "UINT16")
  tensor_uint32 <- as_tf_tensor(arr != 0, .tf_ptype = "UINT32")
  tensor_uint64 <- as_tf_tensor(arr != 0, .tf_ptype = "UINT64")

  expect_identical(as.array(tensor_bool, .ptype = double()), arr)
  expect_identical(as.array(tensor_float, .ptype = double()), arr)
  expect_identical(as.array(tensor_double, .ptype = double()), arr)
  expect_identical(as.array(tensor_int8, .ptype = double()), arr)
  expect_identical(as.array(tensor_int16, .ptype = double()), arr)
  expect_identical(as.array(tensor_int32, .ptype = double()), arr)
  expect_identical(as.array(tensor_int64, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint8, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint16, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint32, .ptype = double()), arr)
  expect_identical(as.array(tensor_uint64, .ptype = double()), arr)

  expect_identical(as.array(tensor_bool, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_float, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_double, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_int64, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint8, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint16, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint32, .ptype = integer()), arr_int)
  expect_identical(as.array(tensor_uint64, .ptype = integer()), arr_int)

  expect_identical(as.array(tensor_uint8, .ptype = raw()), arr_raw)
  expect_identical(as.array(tensor_bool, .ptype = logical()), arr != 0)
})
